/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DebuggerTemplate: typeof import('./src/components/debug/DebuggerTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeviewNodeTemplate: typeof import('./src/components/treeview/TreeviewNodeTemplate.vue')['default']
    TreeviewTemplate: typeof import('./src/components/treeview/TreeviewTemplate.vue')['default']
  }
}
